const Categories = [
  { id: 1, name: "Produits du Terroir", link: "/produits-du-terroir" },
  { id: 2, name: "Huiles (huile d'olive, huile d'argan…)", link: "/huiles" },
  { id: 3, name: "Dattes & Dérivés", link: "/dattes-derives" },
  { id: 4, name: "Miel & Produits de la Ruche", link: "/miel-ruche" },
  { id: 5, name: "Épices & Herbes", link: "/epices-herbes" },
  { id: 6, name: "Couscous & Céréales", link: "/couscous-cereales" },
  { id: 7, name: "Confitures & Produits Sucrés", link: "/confitures-sucres" },
  { id: 8, name: "Plantes Médicinales & Tisanes", link: "/plantes-tisanes" },
  { id: 9, name: "Artisanat", link: "/artisanat" },
  { id: 10, name: "Tapis & Tissages", link: "/tapis-tissages" },
  { id: 11, name: "Poterie & Céramique", link: "/poterie-ceramique" },
  { id: 12, name: "Bijoux Traditionnels", link: "/bijoux-traditionnels" },
  { id: 13, name: "Articles en Bois", link: "/articles-bois" },
  { id: 14, name: "Cuir (sacs, babouches…)", link: "/cuir" },
  { id: 15, name: "Vannerie (paniers, nattes…)", link: "/vannerie" },
  { id: 16, name: "Beauté & Bien-être", link: "/beaute-bien-etre" },
  { id: 17, name: "Produits à base d’Argan", link: "/produits-argan" },
  { id: 18, name: "Savons & Soins Naturels", link: "/savons-soins" },
  { id: 19, name: "Huiles Essentielles", link: "/huiles-essentielles" },
  { id: 20, name: "Parfums Traditionnels", link: "/parfums-traditionnels" },
  { id: 21, name: "Décoration", link: "/decoration" },
  { id: 22, name: "Objets Déco", link: "/objets-deco" },
  { id: 23, name: "Luminaires Artisanaux", link: "/luminaires-artisanaux" },
  { id: 24, name: "Peintures & Calligraphie", link: "/peintures-calligraphie" },
  { id: 25, name: "Articles de Table", link: "/articles-table" },
  { id: 26, name: "Cadeaux & Coffrets", link: "/cadeaux-coffrets" },
  { id: 27, name: "Coffrets Gourmands", link: "/coffrets-gourmands" },
  { id: 28, name: "Packs Bien-être", link: "/packs-bien-etre" },
  { id: 29, name: "Idées Cadeaux Artisanaux", link: "/idees-cadeaux-artisanaux" },
  { id: 30, name: "Mode & Accessoires", link: "/mode-accessoires" },
  { id: 31, name: "Écharpes & Châles", link: "/echarpes-chales" },
  { id: 32, name: "Accessoires en Cuir", link: "/accessoires-cuir" },
  { id: 33, name: "Bijoux Modernes", link: "/bijoux-modernes" },
  { id: 34, name: "Nouveautés", link: "/nouveautes" },
  { id: 35, name: "Derniers Produits", link: "/derniers-produits" },
  { id: 36, name: "Promotions", link: "/promotions" },
  { id: 37, name: "Offres Spéciales", link: "/offres-speciales" },
];

export default Categories;
